- doc/301_text_storyboard.txt
- doc/301_user_stories.txt
Here's the text storyboard file. If there are any issues with it, anyone can make changes to the file in their local branch and create a pull request to staging. Changes to this file are due at 6pm tomorrow, so that we can break its different parts into tasks for Thursday.
Here's also the test user story file. For each user story, we need to complete the rationale, the estimated size in story points and the risk level. For info on how to write a rationale, refer to this link: [Project Part 2 - Product Backlog](https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1505506). Example user stories with rationales can be found at this link: [User Story Examples](https://tech.gsa.gov/guides/user_story_example/).
> added text storyboard and text user stories files

- doc/crc_cards.txt
I updated the crc_cards.txt file with the Owner and User CRC cards.
> added owner and user crc cards

- doc/301_user_stories.txt
The user story sizes and risk levels have been updated, so the only things left to work on for the user stories are the rationales.
> updated user story sizes and risk levels

- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/model/Request.java
- app/src/main/res/layout/fragment_view_book.xml
feat: you can request a book
fix: issue where the viewbookfragment and the homefragment would overlay
added a new request class in model
still working on resolving some issues
> Mahmoud aj

- app/src/main/java/com/example/pocketbook/activity/LoginActivity.java
- app/src/main/java/com/example/pocketbook/activity/SignUpActivity.java
- app/src/main/java/com/example/pocketbook/model/User.java
- app/src/main/res/layout/sign_up.xml
refactor: added the first & last name fields to the sign up page
refactor: added the first & last name fields to the user class and created new getters and setters
feat: Users could add a profile picture from the gallery or the camera when signing up
feat: when a picture is selected the picture is added to the storge and it is saved as username.jpg in the cloud
> Updated the sign up page & added the photo functionality 

- app/build.gradle
- app/src/main/java/com/example/pocketbook/activity/LoginActivity.java
- app/src/main/java/com/example/pocketbook/activity/ViewMyBookActivity.java
- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/EditBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/fragment/OwnedBooksFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileFragment.java
- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/model/BookList.java
- app/src/main/res/layout/fragment_edit_book.xml
- app/src/main/res/layout/fragment_owned_books.xml
- app/src/main/res/values/colors.xml
- app/src/test/java/com/example/pocketbook/BookListTest.java
- app/src/test/java/com/example/pocketbook/util/RequestHandler.java
Switched BookList from an ArrayList to a LinkedHashMap.
>  updated BookList and BookList test

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/pocketbook/activity/SignUpActivity.java
- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
- app/src/main/res/layout/activity_splash_screen.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
The splash activity has been created and other conflicts have been resolved.
> fix: resolved all merge conflicts with staging

- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
Uncomment out the appropriate line to show the login screen.
> refactor: added option to show login after splash screen

- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
fix: changed collection path in viewbookfragment to catalogue instaed of books
> pull request

- app/src/main/java/com/example/pocketbook/fragment/AddFragment.java
Replaced the setBook method with individual setters.
> fix: replaced setBook with individual setters

- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/res/drawable/bg_round_btn_accent.xml
- app/src/main/res/drawable/ic_close.xml
- app/src/main/res/layout/activity_edit_book.xml
- app/src/main/res/layout/alert_dialog_discard_changes.xml
- app/src/main/res/layout/fragment_view_book.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
The layout is set up, but none of the functionality is coded yet.
> refactor: updated EditBookActivity layout

- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/res/layout/activity_edit_book.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Also, ViewMyBookFragment now updates in response to saved changes made in EditBookActivity.
> refactor: added save functionality to EditBookActivity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/res/layout/activity_edit_book.xml
- app/src/main/res/layout/alert_dialog_condition_spinner.xml
Added condition spinner as an AlertDialog.
> refactor: added condition spinner to EditBookActivity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/SignUpActivity.java
- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/model/User.java
- app/src/main/res/layout/activity_edit_book.xml
- app/src/main/res/layout/alert_dialog_book_photo.xml
- app/src/main/res/values/bookConditions.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/file_paths.xml
The text for the condition options now corresponds to a title-cased version of the text that would be permitted in Firebase.
> refactor: replaced condition text with string resources

- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookFragment.java
- app/src/main/java/com/example/pocketbook/model/Book.java
Choosing a photo from the gallery now updates Firebase as well.
> refactor: added choose photo functionality to EditBookActivity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- build.gradle
This build uses gradle 3.4.3, so it should work for everyone.
> refactor: added query to manifest

- app/build.gradle
- app/src/androidTest/java/com/example/pocketbook/AddBookActivityTest.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
The 10 AddBookActivity tests pass.
> feat: added AddBookActivity tests

- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/HomeActivity.java
- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/model/Book.java
The user is only able to access their books through the Profile page now.
> refactor: home fragment only shows other people's books

- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/res/drawable/ic_requested.xml
- app/src/main/res/layout/item_book.xml
- app/src/main/res/values/colors.xml
There is also now a requested icon.
> refactor: added titles and icons to catalogue

- app/src/main/res/layout/fragment_home.xml
The catalogue page now has a toolbar that says Pocketbook.
> refactor: added toolbar to HomeFragment

- app/src/androidTest/java/com/example/pocketbook/activity/SignUpActivityUITest.java
- app/src/main/res/layout/activity_login.xml
SignUpActivityUITest should no longer give an error when the program is run.
> refactor: renamed SignUpActivityUITest

- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/model/RequestList.java
- app/src/main/res/layout/fragment_view_book.xml
- app/src/main/res/layout/fragment_view_my_book_book.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/example/pocketbook/BookTest.java
ViewBookFragment can now navigate back to its calling fragment through the in-page back button.
> refactor: added toolbar to ViewBookFragment

- app/src/main/java/com/example/pocketbook/activity/EditProfileActivity.java
- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/model/User.java
- app/src/test/java/com/example/pocketbook/BookListTest.java
- app/src/test/java/com/example/pocketbook/BookTest.java
- app/src/test/java/com/example/pocketbook/UserTest.java
Book now ensures that the status is one of the valid options.
> refactor: updated BookTest

- app/build.gradle
- app/src/androidTest/java/com/example/pocketbook/ViewBookFragmentTest.java
- app/src/androidTest/java/com/example/pocketbook/ViewMyBookRequestsFragment.java
- app/src/androidTest/java/com/example/pocketbook/activity/AddBookActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/EditBookActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/EditProfileActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/HomeActivityTest.java
- app/src/main/java/com/example/pocketbook/activity/AddBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/adapter/RequestAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/fragment/OwnerFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileFragment.java
- app/src/main/java/com/example/pocketbook/fragment/SearchFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookRequestsFragment.java
- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/model/Notification.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
- app/src/main/java/com/example/pocketbook/util/Parser.java
- app/src/main/java/com/example/pocketbook/util/ScrollUpdate.java
The Parser sections for Request and Notification have been added. Currently, not all tests work with the updated files.
> refactor: updated Parser and FirebaseIntegrity

- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/model/Exchange.java
- app/src/main/java/com/example/pocketbook/model/Location.java
Here are the initial Model files for Location and Exchange.
> feat: added Location and Exchange models

- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/adapter/RequestAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewProfileFragment.java
- app/src/main/res/layout/fragment_view_profile.xml
- app/src/main/res/values/strings.xml
User profiles should now be clickable both from ViewBookFragment and from ViewMyBookRequestsFragment.
> feat: added click functionality to profiles

- app/src/main/java/com/example/pocketbook/adapter/RequestAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/NotificationsFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/notifications/Data.java
- app/src/main/java/com/example/pocketbook/notifications/MyFirebaseMessaging.java
- app/src/main/java/com/example/pocketbook/notifications/OreoNotification.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
- app/src/main/java/com/example/pocketbook/util/MyAppGlideModule.java
- app/src/main/res/layout/fragment_notifications.xml
- app/src/main/res/layout/item_notification.xml
- app/src/main/res/layout/item_notification_counter.xml
a notification delete button just didn't look right so I implemented a swipe instead
> feat: the user can delete a notification by swiping left

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/pocketbook/activity/AddBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/EditProfileActivity.java
- app/src/main/java/com/example/pocketbook/activity/SignUpActivity.java
- app/src/main/java/com/example/pocketbook/util/PhotoHandler.java
All the photo stuff is now handled in PhotoHandler.
> refactor: moved photo stuff into PhotoHandler

- app/src/main/java/com/example/pocketbook/fragment/SetLocationFragment.java
- app/src/main/java/com/example/pocketbook/util/Parser.java
- app/src/main/res/layout/fragment_set_location.xml
setLocation should now alert users to erroneous field entries.
> feat: added text listeners to setLocation

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/pocketbook/activity/AddBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/adapter/LinearBookAdapter.java
- app/src/main/java/com/example/pocketbook/adapter/ProfileAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/fragment/SearchFragment.java
- app/src/main/java/com/example/pocketbook/fragment/SearchMainFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/java/com/example/pocketbook/model/Book.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
- app/src/main/java/com/example/pocketbook/util/KeyboardHandler.java
- app/src/main/java/com/example/pocketbook/util/Parser.java
- app/src/main/res/drawable/rounded.xml
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/layout/fragment_search_main.xml
- app/src/main/res/layout/fragment_view_my_book_book.xml
- app/src/main/res/layout/item_book_linear.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Updated the Search layouts to include search icons.
> refactor: updated Search layouts

- app/src/main/java/com/example/pocketbook/activity/HomeActivity.java
- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/adapter/RequestAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/OwnerFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileFragment.java
- app/src/main/java/com/example/pocketbook/fragment/SetLocationFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewLocationFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookFragment.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
- app/src/main/java/com/example/pocketbook/util/ScanHandler.java
- app/src/main/res/layout/fragment_profile_existing_user.xml
- app/src/main/res/layout/fragment_profile_new_user.xml
- app/src/main/res/layout/fragment_set_location.xml
- app/src/main/res/values/strings.xml
The different exchange actions should work with scanning now.
> refactor: updated ScanHandler with exchange functionalities

- app/src/main/java/com/example/pocketbook/activity/HomeActivity.java
- app/src/main/java/com/example/pocketbook/adapter/ProfilePageAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/BorrowerFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileExistingFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewMyBookBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewProfileFragment.java
- app/src/main/res/layout/fragment_borrower.xml
- app/src/main/res/layout/fragment_profile_existing.xml
- app/src/main/res/layout/fragment_profile_new_user.xml
- app/src/main/res/layout/fragment_view_my_book_book.xml
- app/src/main/res/layout/fragment_view_my_book_requests.xml
- app/src/main/res/values/colors.xml
Clicking on another user's profile picture should now take you to their profile.
> refactor: fixed clicking on other user

- app/src/main/java/com/example/pocketbook/activity/HomeActivity.java
- app/src/main/java/com/example/pocketbook/activity/SplashScreenActivity.java
- app/src/main/java/com/example/pocketbook/notifications/FirebaseMessaging.java
- app/src/main/java/com/example/pocketbook/notifications/NotificationHandler.java
- app/src/main/java/com/example/pocketbook/notifications/OreoNotification.java
- app/src/main/java/com/example/pocketbook/notifications/Response.java
- app/src/main/java/com/example/pocketbook/notifications/Token.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
All users who recently used signed in on the device all will receive notifications, changing that might result in unintended bugs
> fix: multiple users using the same device don't receive notifications intended for other users anymore

- app/src/main/java/com/example/pocketbook/adapter/BookAdapter.java
- app/src/main/java/com/example/pocketbook/adapter/ViewAllBookAdapter.java
- app/src/main/java/com/example/pocketbook/fragment/BorrowedBooksFragment.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/fragment/OwnedBookFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileNewFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ReadyForPickupFragment.java
- app/src/main/java/com/example/pocketbook/fragment/RequestedBooksFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ViewProfileFragment.java
Live updates should work again.
> refactor: reintegrate live update with FirestoreRecyclerAdapter

- app/src/androidTest/java/com/example/pocketbook/activity/AddBookActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/EditBookActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/EditProfileActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/HomeActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/LoginActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/activity/SignUpActivityTest.java
- app/src/androidTest/java/com/example/pocketbook/fragment/ViewBookFragmentTest.java
- app/src/androidTest/java/com/example/pocketbook/fragment/ViewMyBookFragmentTest.java
- app/src/main/java/com/example/pocketbook/activity/EditBookActivity.java
- app/src/main/java/com/example/pocketbook/activity/EditProfileActivity.java
- app/src/main/java/com/example/pocketbook/activity/OnBoardingActivity.java
- app/src/main/java/com/example/pocketbook/fragment/HomeFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileExistingFragment.java
- app/src/main/java/com/example/pocketbook/fragment/ProfileNewFragment.java
- app/src/main/res/layout/activity_edit_profile.xml
- app/src/main/res/layout/activity_on_boarding.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/test/java/com/example/pocketbook/BookTest.java
- app/src/test/java/com/example/pocketbook/RequestTest.java
- app/src/test/java/com/example/pocketbook/util/ParserTest.java
ViewBookFragmentTest should pass now.
> refactor: updated ViewBookFragmentTest

- app/src/main/java/com/example/pocketbook/model/Exchange.java
- app/src/main/java/com/example/pocketbook/model/MeetingDetails.java
- app/src/main/java/com/example/pocketbook/util/FirebaseIntegrity.java
- app/src/main/java/com/example/pocketbook/util/Parser.java
Clicking on the View Location text should now direct the user to the View Location page, regardless of the user's meeting details.
> refactor: updated View Location logic

- .gitignore
- .travis.yml
- app/google-services.json
Added .yml file for Travis configurations.
> feat: added .travis.yml

- app/src/androidTest/java/com/example/pocketbook/fragment/ViewMyBookFragmentTest.java
- app/src/androidTest/java/com/example/pocketbook/fragment/ViewMyBookRequestsFragmentTest.java
checkMyBookRequestsTab test should now pass.
> refactor: updated ViewMyBookRequestsFragmentTest
